version: "3.9"

services:
  db:
    image: postgres:16
    container_name: primerep_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: primerep
    ports:
      - "5432:5432"
    volumes:
      - primerep_pgdata:/var/lib/postgresql/data

volumes:
  primerep_pgdata:
